In [84]:
import nltk
import pandas as pd

In [85]:
from nltk.corpus import brown


In [86]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [87]:
data=brown.sents(categories=['adventure'])

In [88]:
print(data)

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]


In [89]:
data[0]

['Dan',
 'Morgan',
 'told',
 'himself',
 'he',
 'would',
 'forget',
 'Ann',
 'Turner',
 '.']

In [90]:
document=""
for i in range(5):
    document+=" ".join(data[i])
print(document)

Dan Morgan told himself he would forget Ann Turner .He was well rid of her .He certainly didn't want a wife who was fickle as Ann .If he had married her , he'd have been asking for trouble .But all of this was rationalization .


- Data Collection
- Tokenization    ### Break into small parts
- Stopword Removal ### Remove words unnecessary
- Stemming,Lemmatization
- Build a common Vocab
- Vectorise Sentences
- Machine Learning Modelling

In [91]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [92]:
text="What are you doing? I guess you're learning Ml.It is quite an interesting field."

In [93]:
sents=sent_tokenize(text)

In [94]:
print(sents)

['What are you doing?', "I guess you're learning Ml.It is quite an interesting field."]


In [95]:
words=word_tokenize(sents[0])
print(words)

['What', 'are', 'you', 'doing', '?']


## Regular Expression

In [96]:
text="Email me all the 10 class learning assignments of the learn lecture L 1,2,3 at xsd@gmail.com"

In [97]:
sents=sent_tokenize(text)

In [98]:
from nltk.tokenize import RegexpTokenizer

In [99]:
reg_exp="[a-zA-Z@]+"

tokenizer=RegexpTokenizer(reg_exp)
text=tokenizer.tokenize(text)

In [17]:
from nltk.corpus import stopwords

In [18]:
stop=set(stopwords.words('english'))

In [100]:
print(stop)

{'been', 'in', 'more', 'an', 'him', "won't", 'its', 'above', 'has', 'once', "you'll", "wouldn't", 'couldn', 't', "shan't", "you'd", 'be', 'by', 'nor', 're', "haven't", 'where', 'yourself', 'having', 'did', 'into', 'on', 'any', "needn't", 'against', 've', 'myself', 'should', 'ma', 'are', 'needn', 'itself', 'below', "isn't", 'who', 'through', 'than', 'hasn', 'my', "aren't", 'most', "she's", 'd', 'is', 'with', 'just', 'these', "wasn't", 'own', 'yours', 'hers', 'only', 'for', 'can', 'now', 'do', "you're", 'your', 'weren', 'or', "should've", "hasn't", "shouldn't", 'i', 'same', 'ours', "doesn't", 'am', 'off', 'doing', 'a', 'under', 'didn', "didn't", 'up', 'it', 'how', 'if', 'here', 'being', 'some', 'too', 'so', "don't", "mightn't", 'don', 'shan', 'over', 'other', "couldn't", 'will', 'y', 'theirs', 'very', 'o', 'and', 'ain', 'them', 'does', 'which', 'not', 'from', 'all', 'because', 'his', 'there', 'out', 'such', 'themselves', 'while', 'she', 'ourselves', 'whom', 'to', 'both', 'mustn', 'no', '

In [101]:
def remove_stopwords(sent,stopwords):
    useful_words=[w for w in sent if w not in stopwords]
    return useful_words

In [102]:
text=remove_stopwords(text,stop)
print(text)

['Email', 'class', 'learning', 'assignments', 'learn', 'lecture', 'L', 'xsd@gmail', 'com']


# Stemming

In [103]:
print(corpus)

['Dan Morgan told himself he would forget Ann Turner .', 'He was well rid of her .', "He certainly didn't want a wife who was fickle as Ann .", "If he had married her , he'd have been asking for trouble ."]


In [22]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [23]:
ss=SnowballStemmer(language='english')

In [24]:
ls=LancasterStemmer()

In [25]:
ss.stem("jumping")

'jump'

In [26]:
ps=PorterStemmer()

In [27]:
ps.stem('learning')

'learn'

In [28]:
ps.stem('learn')

'learn'

In [29]:
ps.stem('running')

'run'

In [30]:
ps.stem("eat")

'eat'

In [31]:
ps.stem("mouse")

'mous'

In [32]:
ps.stem("teeth")

'teeth'

In [33]:
ps.stem("goose")

'goos'

In [34]:
ps.stem("gosling")

'gosl'

In [35]:
ps.stem("nokia")

'nokia'

In [36]:
ps.stem("abscess")

'abscess'

In [37]:
ps.stem("processing")

'process'

In [38]:
ps.stem("John")

'john'

In [39]:
ss.stem("general")

'general'

In [40]:
ls.stem("general")

'gen'

In [41]:
from nltk.stem import WordNetLemmatizer

In [42]:
wn=WordNetLemmatizer()

In [43]:
wn.lemmatize("resting")

'resting'

In [44]:
wn.lemmatize("morons")

'moron'

In [45]:
data=brown.sents(categories=['adventure'])[:4]

In [46]:
corpus=[' '.join(data[i]) for i in range(4)]
print(corpus)

['Dan Morgan told himself he would forget Ann Turner .', 'He was well rid of her .', "He certainly didn't want a wife who was fickle as Ann .", "If he had married her , he'd have been asking for trouble ."]


In [4]:

from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv=CountVectorizer()

In [49]:
vectorised_data=cv.fit_transform(corpus).toarray()
print (vectorised_data[0])

[1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1]


In [50]:
print ((cv.vocabulary_))


{'dan': 5, 'morgan': 17, 'told': 20, 'himself': 14, 'he': 12, 'would': 28, 'forget': 9, 'ann': 0, 'turner': 22, 'was': 24, 'well': 25, 'rid': 19, 'of': 18, 'her': 13, 'certainly': 4, 'didn': 6, 'want': 23, 'wife': 27, 'who': 26, 'fickle': 7, 'as': 1, 'if': 15, 'had': 10, 'married': 16, 'have': 11, 'been': 3, 'asking': 2, 'for': 8, 'trouble': 21}


In [51]:
cv.inverse_transform(vectorised_data[0])

[array(['ann', 'dan', 'forget', 'he', 'himself', 'morgan', 'told',
        'turner', 'would'], dtype='<U9')]

## Bag of Words

In [52]:
cv=CountVectorizer(tokenizer=tokenizer.tokenize)

In [53]:
cv.fit_transform(corpus).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [54]:
cv.vocabulary_

{'dan': 7,
 'morgan': 19,
 'told': 23,
 'himself': 16,
 'he': 14,
 'would': 31,
 'forget': 11,
 'ann': 1,
 'turner': 25,
 'was': 27,
 'well': 28,
 'rid': 21,
 'of': 20,
 'her': 15,
 'certainly': 5,
 'didn': 8,
 't': 22,
 'want': 26,
 'a': 0,
 'wife': 30,
 'who': 29,
 'fickle': 9,
 'as': 2,
 'if': 17,
 'had': 12,
 'married': 18,
 'd': 6,
 'have': 13,
 'been': 4,
 'asking': 3,
 'for': 10,
 'trouble': 24}

# TF- IDF Normalization

In [55]:
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
tf=TfidfVectorizer()
vd=tf.fit_transform(corpus).toarray()
print(vd)

[[0.28061238 0.         0.         0.         0.         0.35592122
  0.         0.         0.         0.35592122 0.         0.
  0.18573446 0.         0.35592122 0.         0.         0.35592122
  0.         0.         0.35592122 0.         0.35592122 0.
  0.         0.         0.         0.         0.35592122]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.24557576 0.37102215 0.         0.         0.         0.
  0.47059455 0.47059455 0.         0.         0.         0.
  0.37102215 0.47059455 0.         0.         0.        ]
 [0.27017662 0.34268479 0.         0.         0.34268479 0.
  0.34268479 0.34268479 0.         0.         0.         0.
  0.17882714 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.34268479
  0.27017662 0.         0.34268479 0.34268479 0.        ]
 [0.         0.         0.32090095 0.32090095 0.         0.
  0.         0.       

In [57]:
print(vd[0])

[0.28061238 0.         0.         0.         0.         0.35592122
 0.         0.         0.         0.35592122 0.         0.
 0.18573446 0.         0.35592122 0.         0.         0.35592122
 0.         0.         0.35592122 0.         0.35592122 0.
 0.         0.         0.         0.         0.35592122]


In [58]:
tf.vocabulary_

{'dan': 5,
 'morgan': 17,
 'told': 20,
 'himself': 14,
 'he': 12,
 'would': 28,
 'forget': 9,
 'ann': 0,
 'turner': 22,
 'was': 24,
 'well': 25,
 'rid': 19,
 'of': 18,
 'her': 13,
 'certainly': 4,
 'didn': 6,
 'want': 23,
 'wife': 27,
 'who': 26,
 'fickle': 7,
 'as': 1,
 'if': 15,
 'had': 10,
 'married': 16,
 'have': 11,
 'been': 3,
 'asking': 2,
 'for': 8,
 'trouble': 21}

In [59]:
from sklearn.datasets import fetch_20newsgroups

In [74]:
newsgroups=fetch_20newsgroups()

In [75]:
Xa=newsgroups.data
Y=newsgroups.target_names

In [111]:
print(len(Xa))

11314


In [126]:
sents=sent_tokenize(str(Xa[1]))
text=tokenizer.tokenize(str(sents))

In [127]:
print(text)


['From', 'guykuo@carson', 'u', 'washington', 'edu', 'Guy', 'Kuo', 'nSubject', 'SI', 'Clock', 'Poll', 'Final', 'Call', 'nSummary', 'Final', 'call', 'for', 'SI', 'clock', 'reports', 'nKeywords', 'SI', 'acceleration', 'clock', 'upgrade', 'nArticle', 'I', 'D', 'shelley', 'qvfo', 'INNc', 's', 'nOrganization', 'University', 'of', 'Washington', 'nLines', 'nNNTP', 'Posting', 'Host', 'carson', 'u', 'washington', 'edu', 'n', 'nA', 'fair', 'number', 'of', 'brave', 'souls', 'who', 'upgraded', 'their', 'SI', 'clock', 'oscillator', 'have', 'nshared', 'their', 'experiences', 'for', 'this', 'poll', 'Please', 'send', 'a', 'brief', 'message', 'detailing', 'nyour', 'experiences', 'with', 'the', 'procedure', 'Top', 'speed', 'attained', 'CPU', 'rated', 'speed', 'nadd', 'on', 'cards', 'and', 'adapters', 'heat', 'sinks', 'hour', 'of', 'usage', 'per', 'day', 'floppy', 'disk', 'nfunctionality', 'with', 'and', 'm', 'floppies', 'are', 'especially', 'requested', 'n', 'nI', 'will', 'be', 'summarizing', 'in', 'the'

In [112]:
c=[]

for i in range(len(Xa)):
    m=" ".join(Xa[i])
    c.append(m)


In [113]:
Y

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [116]:
for i in range (len(c)):
    c[i]=remove_stopwords(c[i][0],stop)
print(c[1])

['F']


In [ ]:
all_y=newsgroups.target

In [ ]:
print(len(all_y))

In [ ]:
X=[Xa[i] for i in range(len(Xa)) if all_y[i]<=4]
print(len(X))

In [83]:
tf=TfidfVectorizer()
t=tf.fit_transform(X).toarray()


NameError: name 'X' is not defined

In [217]:
X_train=t[:2790]    
X_train=np.array(X_train)

MemoryError: 

In [97]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [98]:
X_test=t[1000:]

In [99]:
print(X_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [100]:
Y_o=[Y[all_y[i]] for i in range(len(all_y)) if all_y[i]<=4]


In [101]:
Y_o=np.array(Y_o)
print(Y_o.shape)

(2823,)


In [102]:
Y_train=Y_o[:1000]

In [103]:
Y_test=Y_o[1000:]

In [104]:
def distance(p1,p2):
    return np.sum((p2 - p1)**2)**.5

In [105]:
def knn(X,Y,test,k=5):
    m = X.shape[0]
    
    d = []
    for i  in range(m):
        dist = distance(test,X[i])
        d.append((dist,Y[i]))
    
    d = np.array(sorted(d))[:,1]
    d = d[:k]
    t =  np.unique(d,return_counts=True)
    idx = np.argmax(t[1])
    pred = (t[0][idx])
    
    return pred
    

In [106]:
print(Y_train[1])

comp.sys.mac.hardware


In [107]:
ans=[]

In [123]:
for i in range(X_test.shape[0]):
    ans.append(knn(X_train,Y_train,X_test[i,:],5))

In [111]:
a=pd.DataFrame(data=ans,columns=["target"])

In [112]:
a.to_csv("result.csv",index=False)

In [ ]:
tf=TfidfVectorizer()
=tf.fit_transform(X).toarray()
print(tf.vocabulary_)

In [ ]:
vd2=cv.fit_transform(X_train).toarray()

In [127]:
acc=0
for i in range(len(Y_train)):
    if(Y_train[i]==ans[i]):
        acc+=1

In [128]:
print(acc)

208


In [126]:
len(Y_train)

1000

In [8]:
import cv2

In [11]:
cv2.imshow?